version: "3.8"

services:
  naghoos:
    image: ghcr.io/${GITHUB_USERNAME}/naghoos:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
